# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build the .ipa for sideloading"
  lane :build_ipa do
    gym(
      scheme: "WorkoutTracker",
      export_method: "development",
      include_bitcode: false,
      include_symbols: false,
      output_directory: "./build",
      output_name: "WorkoutTracker.ipa",
      export_xcargs: "-allowProvisioningUpdates"
    )
  end

  desc "Description of what the lane does"
  lane :custom_lane do
    build_ipa
  end
end
